application: pythea-levi
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence
- warmup

handlers:
- url: /css
  static_dir: css

- url: /info
  static_dir: info

- url: /images
  static_dir: images

- url: /js
  static_dir: js
  
- url: /html
  static_dir: html

- url: /admin/.*
  script: main.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py

builtins:
- deferred: on
- remote_api: on

admin_console:
 pages:
 - name: Appstats
   url: /stats
