application: pythea-levi
version: hans
runtime: python
api_version: 1

inbound_services:
- channel_presence
- warmup

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js
  
- url: /html
  static_dir: html

- url: /.*
  script: main.py

builtins:
- deferred: on
- remote_api: on
